// <auto-generated>
// EPMS Enterprise Server — Database Custom Actions
// These actions run during WiX installation to set up the database infrastructure.
// </auto-generated>

using System;
using System.Diagnostics;
using System.IO;
using System.Threading;
using WixToolset.Dtf.WindowsInstaller;
using Npgsql;

namespace EPMS.CustomActions
{
    /// <summary>
    /// Custom actions for PostgreSQL database installation and configuration.
    /// </summary>
    public class DatabaseActions
    {
        /// <summary>
        /// Installs embedded PostgreSQL if selected during setup.
        /// Runs the PostgreSQL installer in silent mode with pre-configured options.
        /// </summary>
        [CustomAction]
        public static ActionResult InstallPostgreSQL(Session session)
        {
            session.Log("Starting PostgreSQL embedded installation...");

            try
            {
                string installPath = session.CustomActionData["INSTALLFOLDER"];
                string dataPath = Path.Combine(installPath, "data", "pgsql");
                string pgInstaller = Path.Combine(installPath, "postgresql-16.4-1-windows-x64.exe");

                if (!File.Exists(pgInstaller))
                {
                    session.Log($"PostgreSQL installer not found at: {pgInstaller}");
                    return ActionResult.Failure;
                }

                // Install PostgreSQL silently
                // Uses the embedded PostgreSQL installer with pre-configured options
                ProcessStartInfo psi = new ProcessStartInfo
                {
                    FileName = pgInstaller,
                    Arguments = $"--mode unattended --prefix \"{dataPath}\" " +
                                $"--datadir \"{dataPath}\\data\" " +
                                $"--serverport {session.CustomActionData["EPMS_DB_PORT"]} " +
                                $"--superpassword \"{session.CustomActionData["EPMS_DB_PASSWORD"]}\" " +
                                $"--enable_acledit 0",
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true
                };

                using (Process process = Process.Start(psi))
                {
                    process.WaitForExit(120000); // 2-minute timeout
                    if (process.ExitCode != 0)
                    {
                        string error = process.StandardError.ReadToEnd();
                        session.Log($"PostgreSQL installation failed with exit code {process.ExitCode}: {error}");
                        return ActionResult.Failure;
                    }
                }

                // Register PostgreSQL as a Windows service
                string pgCtlPath = Path.Combine(dataPath, "bin", "pg_ctl.exe");
                if (File.Exists(pgCtlPath))
                {
                    Process.Start(pgCtlPath, $"register -N epms-postgresql-16 -D \"{dataPath}\\data\" -w").WaitForExit(30000);
                }

                session.Log("PostgreSQL installed successfully.");
                return ActionResult.Success;
            }
            catch (Exception ex)
            {
                session.Log($"PostgreSQL installation error: {ex.Message}");
                return ActionResult.Failure;
            }
        }

        /// <summary>
        /// Creates the EPMS database and initial schema.
        /// </summary>
        [CustomAction]
        public static ActionResult CreateDatabase(Session session)
        {
            session.Log("Creating EPMS database...");

            try
            {
                string host = session.CustomActionData["EPMS_DB_HOST"] ?? "localhost";
                string port = session.CustomActionData["EPMS_DB_PORT"] ?? "5432";
                string password = session.CustomActionData["EPMS_DB_PASSWORD"];

                // Wait for PostgreSQL to be ready
                Thread.Sleep(5000);

                // Connect and create database
                string masterConnectionString = $"Host={host};Port={port};Database=postgres;Username=postgres;Password={password};Timeout=30";
                string epmsConnectionString = $"Host={host};Port={port};Database=epms;Username=postgres;Password={password};Timeout=30";

                using (var conn = new NpgsqlConnection(masterConnectionString))
                {
                    conn.Open();

                    // Check if database exists
                    using (var cmd = new NpgsqlCommand("SELECT 1 FROM pg_database WHERE datname = 'epms'", conn))
                    {
                        var exists = cmd.ExecuteScalar();
                        if (exists == null)
                        {
                            // Create database
                            using (var createCmd = new NpgsqlCommand("CREATE DATABASE epms WITH ENCODING 'UTF8' LC_COLLATE 'English_United States.1252'", conn))
                            {
                                createCmd.ExecuteNonQuery();
                            }
                            session.Log("EPMS database created successfully.");
                        }
                        else
                        {
                            session.Log("EPMS database already exists.");
                        }
                    }
                }

                // Enable required extensions
                using (var conn = new NpgsqlConnection(epmsConnectionString))
                {
                    conn.Open();
                    string[] extensions = { "uuid-ossp", "pgcrypto", "pg_stat_statements" };
                    foreach (var ext in extensions)
                    {
                        using (var cmd = new NpgsqlCommand($"CREATE EXTENSION IF NOT EXISTS \"{ext}\"", conn))
                        {
                            cmd.ExecuteNonQuery();
                        }
                    }
                    session.Log("Database extensions enabled.");
                }

                session.Log("EPMS database creation completed.");
                return ActionResult.Success;
            }
            catch (Exception ex)
            {
                session.Log($"Database creation error: {ex.Message}");
                return ActionResult.Failure;
            }
        }

        /// <summary>
        /// Runs SQL migration scripts to initialize the database schema.
        /// </summary>
        [CustomAction]
        public static ActionResult RunMigrations(Session session)
        {
            session.Log("Running database migrations...");

            try
            {
                string installPath = session.CustomActionData["INSTALLFOLDER"];
                string host = session.CustomActionData["EPMS_DB_HOST"] ?? "localhost";
                string port = session.CustomActionData["EPMS_DB_PORT"] ?? "5432";
                string password = session.CustomActionData["EPMS_DB_PASSWORD"];
                string sqlPath = Path.Combine(installPath, "sql");

                string connectionString = $"Host={host};Port={port};Database=epms;Username=postgres;Password={password};Timeout=120";

                using (var conn = new NpgsqlConnection(connectionString))
                {
                    conn.Open();

                    // Run migration scripts in order
                    string[] sqlFiles = { "001_initial_schema.sql", "002_seed_data.sql", "003_indexes.sql" };
                    foreach (var file in sqlFiles)
                    {
                        string filePath = Path.Combine(sqlPath, file);
                        if (File.Exists(filePath))
                        {
                            string sql = File.ReadAllText(filePath);
                            using (var cmd = new NpgsqlCommand(sql, conn))
                            {
                                cmd.ExecuteNonQuery();
                            }
                            session.Log($"Executed migration: {file}");
                        }
                        else
                        {
                            session.Log($"Migration file not found: {filePath}");
                        }
                    }
                }

                session.Log("Database migrations completed successfully.");
                return ActionResult.Success;
            }
            catch (Exception ex)
            {
                session.Log($"Migration error: {ex.Message}");
                return ActionResult.Failure;
            }
        }

        /// <summary>
        /// Rollback handler for PostgreSQL installation.
        /// </summary>
        [CustomAction]
        public static ActionResult RollbackPostgreSQL(Session session)
        {
            session.Log("Rolling back PostgreSQL installation...");
            try
            {
                // Stop and remove PostgreSQL service
                Process.Start("sc", "stop epms-postgresql-16").WaitForExit(10000);
                Process.Start("sc", "delete epms-postgresql-16").WaitForExit(5000);
                session.Log("PostgreSQL rollback completed.");
            }
            catch (Exception ex)
            {
                session.Log($"Rollback warning: {ex.Message}");
            }
            return ActionResult.Success;
        }

        /// <summary>
        /// Rollback handler for database creation.
        /// </summary>
        [CustomAction]
        public static ActionResult RollbackDatabase(Session session)
        {
            session.Log("Rolling back database creation...");
            try
            {
                string host = session.CustomActionData["EPMS_DB_HOST"] ?? "localhost";
                string port = session.CustomActionData["EPMS_DB_PORT"] ?? "5432";
                string password = session.CustomActionData["EPMS_DB_PASSWORD"];
                string connectionString = $"Host={host};Port={port};Database=postgres;Username=postgres;Password={password};Timeout=30";

                using (var conn = new NpgsqlConnection(connectionString))
                {
                    conn.Open();
                    // Terminate connections and drop database
                    using (var cmd = new NpgsqlCommand(
                        "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity " +
                        "WHERE pg_stat_activity.datname = 'epms' AND pid <> pg_backend_pid()", conn))
                    {
                        cmd.ExecuteNonQuery();
                    }
                    using (var cmd = new NpgsqlCommand("DROP DATABASE IF EXISTS epms", conn))
                    {
                        cmd.ExecuteNonQuery();
                    }
                }
                session.Log("Database rollback completed.");
            }
            catch (Exception ex)
            {
                session.Log($"Rollback warning: {ex.Message}");
            }
            return ActionResult.Success;
        }
    }
}
